"""Add payment support

Revision ID: 02a98ec0d229
Revises: 19a86462cedf
Create Date: 2026-02-15 21:25:30.340195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02a98ec0d229'
down_revision: Union[str, Sequence[str], None] = '19a86462cedf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wechat_qr_code_url', sa.String(length=500), nullable=True),
    sa.Column('payment_instructions_en', sa.Text(), nullable=True),
    sa.Column('payment_instructions_zh', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_packages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('name_zh', sa.String(length=200), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('description_zh', sa.Text(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('registration_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['class_packages.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    op.add_column('classes', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('classes', sa.Column('currency', sa.String(length=10), server_default='CNY', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'currency')
    op.drop_column('classes', 'price')
    op.drop_table('payments')
    op.drop_table('class_packages')
    op.drop_table('payment_settings')
    # ### end Alembic commands ###
