"""add tracking_tokens table

Revision ID: 268f5619f962
Revises: b647922abf3c
Create Date: 2026-02-17 20:18:02.861600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '268f5619f962'
down_revision: Union[str, Sequence[str], None] = 'b647922abf3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_tokens_email'), 'tracking_tokens', ['email'], unique=True)
    op.create_index(op.f('ix_tracking_tokens_token'), 'tracking_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracking_tokens_token'), table_name='tracking_tokens')
    op.drop_index(op.f('ix_tracking_tokens_email'), table_name='tracking_tokens')
    op.drop_table('tracking_tokens')
    # ### end Alembic commands ###
