"""Add Venmo payment support and dual pricing

Revision ID: 5fb47ed06aeb
Revises: 02a98ec0d229
Create Date: 2026-02-16 09:32:50.250123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb47ed06aeb'
down_revision: Union[str, Sequence[str], None] = '02a98ec0d229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_packages', sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('classes', sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('payment_settings', sa.Column('venmo_qr_code_url', sa.String(length=500), nullable=True))
    op.add_column('payment_settings', sa.Column('venmo_payment_instructions_en', sa.Text(), nullable=True))
    op.add_column('payment_settings', sa.Column('venmo_payment_instructions_zh', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_settings', 'venmo_payment_instructions_zh')
    op.drop_column('payment_settings', 'venmo_payment_instructions_en')
    op.drop_column('payment_settings', 'venmo_qr_code_url')
    op.drop_column('classes', 'price_usd')
    op.drop_column('class_packages', 'price_usd')
    # ### end Alembic commands ###
