"""add consent_records table

Revision ID: b647922abf3c
Revises: 005_add_class_location
Create Date: 2026-02-17 15:30:46.688306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b647922abf3c'
down_revision: Union[str, Sequence[str], None] = '005_add_class_location'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('yoga_type_id', sa.Uuid(), nullable=False),
    sa.Column('consent_text_version', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['yoga_type_id'], ['yoga_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'yoga_type_id', name='uq_consent_email_yoga_type')
    )
    op.create_index(op.f('ix_consent_records_email'), 'consent_records', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consent_records_email'), table_name='consent_records')
    op.drop_table('consent_records')
    # ### end Alembic commands ###
